import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import clsx from "clsx";
import "./globals.css";
import Navbar from "./_components/Navbar";
import Footer from "./_components/Footer";

const poppins = Poppins({
  weight: ["400", "500", "700"],
  subsets: ["devanagari", "latin", "latin-ext"],
});

export const metadata: Metadata = {
  applicationName: 'Careerblob',
  appleWebApp: true,
  formatDetection: { telephone: false },
  title: "Create Next App",
  description: "Generated by create next app",
  manifest: '/manifest.json',
  icons: {
    apple: '/icon-192x192.png'
  },
  themeColor: '#211670'
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={clsx("bg-background", poppins.className)}>
        <ClerkProvider>
          <Navbar />
          {children}
          <Footer />
        </ClerkProvider>
      </body>
    </html>
  );
}
